/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b91a24",
        "on-primary": "#68000a",
        "on-tertiary-container": "#00302e",
        "tertiary-container": "#24a09d",
        "error": "#ffb4ab",
        "surface-dim": "#1e100e",
        "surface-container-lowest": "#180a09",
        "surface-container-highest": "#42302f",
        "surface-container-low": "#271816",
        "surface": "#1e100e",
        "surface-container-high": "#372624",
        "primary-container": "#ff5451",
        "background": "#1e100e",
        "on-error": "#690005",
        "on-tertiary-fixed": "#00201f",
        "tertiary": "#69d8d4",
        "tertiary-fixed-dim": "#69d8d4",
        "on-secondary-fixed": "#2a1700",
        "secondary-fixed": "#ffddb8",
        "on-surface": "#f9dcd9",
        "on-primary-fixed-variant": "#930013",
        "on-surface-variant": "#e4beba",
        "outline": "#ab8986",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary-fixed": "#87f4f0",
        "secondary": "#ffb95f",
        "error-container": "#93000a",
        "secondary-container": "#ee9800",
        "on-secondary": "#472a00",
        "inverse-surface": "#f9dcd9",
        "on-tertiary": "#003736",
        "on-secondary-container": "#5b3800",
        "secondary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#00504e",
        "surface-container": "#2c1c1a",
        "primary-fixed": "#ffdad7",
        "surface-bright": "#473533",
        "surface-variant": "#42302f",
        "primary-fixed-dim": "#ffb3ad",
        "inverse-on-surface": "#3e2c2b",
        "on-primary-container": "#5c0008",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#410004",
        "on-background": "#f9dcd9",
        "primary": "#ffb3ad",
        "outline-variant": "#5b403e",
        "surface-tint": "#ffb3ad"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-sm": "12px",
        "container-max": "1280px",
        "base": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
    }
  },
  plugins: [],
};
